//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the UtilitiesData datasource.
    /// </summary>
    public sealed partial class UtilitiesDataService
        : global::LightSwitchApplication.UtilitiesData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UtilitiesDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_Inserting(global::LightSwitchApplication.CatalogueItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_Inserted(global::LightSwitchApplication.CatalogueItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_Updating(global::LightSwitchApplication.CatalogueItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_Updated(global::LightSwitchApplication.CatalogueItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_Deleting(global::LightSwitchApplication.CatalogueItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_Deleted(global::LightSwitchApplication.CatalogueItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogueItems_Validate(global::LightSwitchApplication.CatalogueItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_Inserting(global::LightSwitchApplication.KeyNameValue entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_Inserted(global::LightSwitchApplication.KeyNameValue entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_Updating(global::LightSwitchApplication.KeyNameValue entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_Updated(global::LightSwitchApplication.KeyNameValue entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_Deleting(global::LightSwitchApplication.KeyNameValue entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_Deleted(global::LightSwitchApplication.KeyNameValue entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeyNameValues_Validate(global::LightSwitchApplication.KeyNameValue entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_Inserting(global::LightSwitchApplication.Person entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_Inserted(global::LightSwitchApplication.Person entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_Updating(global::LightSwitchApplication.Person entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_Updated(global::LightSwitchApplication.Person entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_Deleting(global::LightSwitchApplication.Person entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_Deleted(global::LightSwitchApplication.Person entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Persons_Validate(global::LightSwitchApplication.Person entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_Inserting(global::LightSwitchApplication.Task entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_Inserted(global::LightSwitchApplication.Task entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_Updating(global::LightSwitchApplication.Task entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_Updated(global::LightSwitchApplication.Task entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_Deleting(global::LightSwitchApplication.Task entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_Deleted(global::LightSwitchApplication.Task entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tasks_Validate(global::LightSwitchApplication.Task entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UtilitiesData_SendingRequest(global::Microsoft.LightSwitch.ODataSendingState state);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UtilitiesData_ReceivedResponse(global::Microsoft.LightSwitch.ODataReceivedState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.CatalogueItem>
                __CatalogueItemsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.CatalogueItem>(
                    "CatalogueItems",
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_CanInsert,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_CanUpdate,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_CanDelete,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_CanRead,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_Inserting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_Inserted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_Updating,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_Updated,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_Deleting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_Deleted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__CatalogueItems_Validate,
                    null);
            private static bool __CatalogueItems_CanInsert(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.CatalogueItems_CanInsert(ref result);
                return result;
            }
            private static bool __CatalogueItems_CanUpdate(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.CatalogueItems_CanUpdate(ref result);
                return result;
            }
            private static bool __CatalogueItems_CanDelete(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.CatalogueItems_CanDelete(ref result);
                return result;
            }
            private static bool __CatalogueItems_CanRead(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.CatalogueItems_CanRead(ref result);
                return result;
            }
            private static void __CatalogueItems_Inserting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.CatalogueItem e)
            {
                d.CatalogueItems_Inserting(e);
            }
            private static void __CatalogueItems_Inserted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.CatalogueItem e)
            {
                d.CatalogueItems_Inserted(e);
            }
            private static void __CatalogueItems_Updating(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.CatalogueItem e)
            {
                d.CatalogueItems_Updating(e);
            }
            private static void __CatalogueItems_Updated(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.CatalogueItem e)
            {
                d.CatalogueItems_Updated(e);
            }
            private static void __CatalogueItems_Deleting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.CatalogueItem e)
            {
                d.CatalogueItems_Deleting(e);
            }
            private static void __CatalogueItems_Deleted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.CatalogueItem e)
            {
                d.CatalogueItems_Deleted(e);
            }
            private static void __CatalogueItems_Validate(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.CatalogueItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.CatalogueItems_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.KeyNameValue>
                __KeyNameValuesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.KeyNameValue>(
                    "KeyNameValues",
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_CanInsert,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_CanUpdate,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_CanDelete,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_CanRead,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_Inserting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_Inserted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_Updating,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_Updated,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_Deleting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_Deleted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__KeyNameValues_Validate,
                    null);
            private static bool __KeyNameValues_CanInsert(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.KeyNameValues_CanInsert(ref result);
                return result;
            }
            private static bool __KeyNameValues_CanUpdate(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.KeyNameValues_CanUpdate(ref result);
                return result;
            }
            private static bool __KeyNameValues_CanDelete(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.KeyNameValues_CanDelete(ref result);
                return result;
            }
            private static bool __KeyNameValues_CanRead(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.KeyNameValues_CanRead(ref result);
                return result;
            }
            private static void __KeyNameValues_Inserting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.KeyNameValue e)
            {
                d.KeyNameValues_Inserting(e);
            }
            private static void __KeyNameValues_Inserted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.KeyNameValue e)
            {
                d.KeyNameValues_Inserted(e);
            }
            private static void __KeyNameValues_Updating(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.KeyNameValue e)
            {
                d.KeyNameValues_Updating(e);
            }
            private static void __KeyNameValues_Updated(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.KeyNameValue e)
            {
                d.KeyNameValues_Updated(e);
            }
            private static void __KeyNameValues_Deleting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.KeyNameValue e)
            {
                d.KeyNameValues_Deleting(e);
            }
            private static void __KeyNameValues_Deleted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.KeyNameValue e)
            {
                d.KeyNameValues_Deleted(e);
            }
            private static void __KeyNameValues_Validate(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.KeyNameValue e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.KeyNameValues_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.Person>
                __PersonsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.Person>(
                    "Persons",
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_CanInsert,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_CanUpdate,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_CanDelete,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_CanRead,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_Inserting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_Inserted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_Updating,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_Updated,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_Deleting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_Deleted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Persons_Validate,
                    null);
            private static bool __Persons_CanInsert(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Persons_CanInsert(ref result);
                return result;
            }
            private static bool __Persons_CanUpdate(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Persons_CanUpdate(ref result);
                return result;
            }
            private static bool __Persons_CanDelete(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Persons_CanDelete(ref result);
                return result;
            }
            private static bool __Persons_CanRead(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Persons_CanRead(ref result);
                return result;
            }
            private static void __Persons_Inserting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Person e)
            {
                d.Persons_Inserting(e);
            }
            private static void __Persons_Inserted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Person e)
            {
                d.Persons_Inserted(e);
            }
            private static void __Persons_Updating(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Person e)
            {
                d.Persons_Updating(e);
            }
            private static void __Persons_Updated(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Person e)
            {
                d.Persons_Updated(e);
            }
            private static void __Persons_Deleting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Person e)
            {
                d.Persons_Deleting(e);
            }
            private static void __Persons_Deleted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Person e)
            {
                d.Persons_Deleted(e);
            }
            private static void __Persons_Validate(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Person e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Persons_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.Task>
                __TasksEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.UtilitiesDataService, global::LightSwitchApplication.Task>(
                    "Tasks",
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_CanInsert,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_CanUpdate,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_CanDelete,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_CanRead,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_Inserting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_Inserted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_Updating,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_Updated,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_Deleting,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_Deleted,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Tasks_Validate,
                    null);
            private static bool __Tasks_CanInsert(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Tasks_CanInsert(ref result);
                return result;
            }
            private static bool __Tasks_CanUpdate(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Tasks_CanUpdate(ref result);
                return result;
            }
            private static bool __Tasks_CanDelete(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Tasks_CanDelete(ref result);
                return result;
            }
            private static bool __Tasks_CanRead(global::LightSwitchApplication.UtilitiesDataService d)
            {
                bool result = true;
                d.Tasks_CanRead(ref result);
                return result;
            }
            private static void __Tasks_Inserting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Task e)
            {
                d.Tasks_Inserting(e);
            }
            private static void __Tasks_Inserted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Task e)
            {
                d.Tasks_Inserted(e);
            }
            private static void __Tasks_Updating(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Task e)
            {
                d.Tasks_Updating(e);
            }
            private static void __Tasks_Updated(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Task e)
            {
                d.Tasks_Updated(e);
            }
            private static void __Tasks_Deleting(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Task e)
            {
                d.Tasks_Deleting(e);
            }
            private static void __Tasks_Deleted(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Task e)
            {
                d.Tasks_Deleted(e);
            }
            private static void __Tasks_Validate(global::LightSwitchApplication.UtilitiesDataService d, global::LightSwitchApplication.Task e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Tasks_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.UtilitiesDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.UtilitiesDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.UtilitiesDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.UtilitiesDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.UtilitiesDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.UtilitiesDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.UtilitiesDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.UtilitiesDataService>(
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.UtilitiesDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.UtilitiesDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.UtilitiesDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.ODataServiceAuthEntry<global::LightSwitchApplication.UtilitiesDataService>
                ___ODataServiceAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.ODataServiceAuthEntry<global::LightSwitchApplication.UtilitiesDataService>(
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__UtilitiesData_SendingRequest,
                    global::LightSwitchApplication.UtilitiesDataService.DetailsClass.__UtilitiesData_ReceivedResponse);
            private static void __UtilitiesData_SendingRequest(global::LightSwitchApplication.UtilitiesDataService d, global::Microsoft.LightSwitch.ODataSendingState state)
            {
                d.UtilitiesData_SendingRequest(state);
            }
            private static void __UtilitiesData_ReceivedResponse(global::LightSwitchApplication.UtilitiesDataService d, global::Microsoft.LightSwitch.ODataReceivedState state)
            {
                d.UtilitiesData_ReceivedResponse(state);
            }
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the DiagnosticsData datasource.
    /// </summary>
    public sealed partial class DiagnosticsDataService
        : global::LightSwitchApplication.DiagnosticsData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DiagnosticsDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Endpoints_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Endpoints_Validate(global::LightSwitchApplication.Endpoint entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DiagnosticsData_SendingRequest(global::Microsoft.LightSwitch.ODataSendingState state);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DiagnosticsData_ReceivedResponse(global::Microsoft.LightSwitch.ODataReceivedState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DiagnosticsDataService, global::LightSwitchApplication.Endpoint>
                __EndpointsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DiagnosticsDataService, global::LightSwitchApplication.Endpoint>(
                    "Endpoints",
                    null,
                    null,
                    null,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__Endpoints_CanRead,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__Endpoints_Validate,
                    null);
            private static bool __Endpoints_CanRead(global::LightSwitchApplication.DiagnosticsDataService d)
            {
                bool result = true;
                d.Endpoints_CanRead(ref result);
                return result;
            }
            private static void __Endpoints_Validate(global::LightSwitchApplication.DiagnosticsDataService d, global::LightSwitchApplication.Endpoint e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Endpoints_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.DiagnosticsDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.DiagnosticsDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.DiagnosticsDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.DiagnosticsDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.DiagnosticsDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.DiagnosticsDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.DiagnosticsDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.DiagnosticsDataService>(
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.DiagnosticsDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.DiagnosticsDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.DiagnosticsDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.ODataServiceAuthEntry<global::LightSwitchApplication.DiagnosticsDataService>
                ___ODataServiceAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.ODataServiceAuthEntry<global::LightSwitchApplication.DiagnosticsDataService>(
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__DiagnosticsData_SendingRequest,
                    global::LightSwitchApplication.DiagnosticsDataService.DetailsClass.__DiagnosticsData_ReceivedResponse);
            private static void __DiagnosticsData_SendingRequest(global::LightSwitchApplication.DiagnosticsDataService d, global::Microsoft.LightSwitch.ODataSendingState state)
            {
                d.DiagnosticsData_SendingRequest(state);
            }
            private static void __DiagnosticsData_ReceivedResponse(global::LightSwitchApplication.DiagnosticsDataService d, global::Microsoft.LightSwitch.ODataReceivedState state)
            {
                d.DiagnosticsData_ReceivedResponse(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
