// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/AddEditEndpoint.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/AddEditKeyNameValue.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/AddEditTask.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/ViewEndpoint.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/ViewKeyNameValue.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/ViewTask.lsml.js\"></script>");
